# Generated by Django 5.0.6 on 2024-05-31 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0003_person_icecream_alter_bb_published_icecreamstand_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='child',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Ребенок', 'verbose_name_plural': 'Дети'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Человек', 'verbose_name_plural': 'Люди'},
        ),
        migrations.RenameField(
            model_name='icecream',
            old_name='kg',
            new_name='quantity_kg',
        ),
        migrations.AlterField(
            model_name='child',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='bboard.person', verbose_name='Родитель'),
        ),
        migrations.AlterField(
            model_name='icecreamstand',
            name='ice_creams',
            field=models.ManyToManyField(related_name='stands', to='bboard.icecream', verbose_name='Мороженое'),
        ),
    ]
